#!/usr/bin/env tsx
/**
 * Regenerates the committed pi-coding-agent gate snapshots (issue #420, the
 * gate evidence bundle for the pi-coding-agent phase, ADR 0036).
 *
 * The bundle mirrors the pi-ai/pi-tui strategy: the README pins the frozen
 * baseline commit and the `@earendil-works/pi-coding-agent@0.83.0` artifact,
 * and this sidecar regenerates every committed snapshot from the frozen pi
 * checkout deterministically under the sanitization rules.
 *
 * Currently owned snapshots:
 *
 *   - `e2e/boot.txt` + `e2e/turn.txt` — the committed CLI-level screen
 *     goldens of the interactive-boot-through-an-agent-turn E2E (#399),
 *     generated by `tests/coding_agent/tui/InteractiveBootE2ETest.cpp` under
 *     `CCH_CAPTURE_GOLDENS=1` and byte-compared by the same test. The sidecar
 *     drives the test binary once in capture mode (regenerates the goldens)
 *     and once in compare mode (byte-verifies them against the freshly
 *     written files), so a nondeterministic capture fails loudly.
 *
 * The differential-golden families land with their own tickets and extend
 * this sidecar with further capture sections: the session/value suites and
 * the System Prompt golden (#421), and the interactive/rendering goldens
 * (#422). The canonical projection helpers below are the shared seam those
 * families use, mirroring `fixtures/pi-ai/capture/capture-ts-events.mts`
 * (the R2 §7.8 projection rules).
 *
 * Sanitization rules (see `fixtures/pi-coding-agent/README.md`):
 *   - deterministic environment — HOME/USERPROFILE pinned, terminal-emulator
 *     variables scrubbed before any module reads them;
 *   - dummy data only — the E2E workspace lives at the deterministic
 *     `cpp-harness-e2e-workspace` temp path, recreated at boot; session
 *     histories are fixture-authored, never copied from a live session;
 *   - scrubbed paths — no real `~/.pi/agent/auth.json` / `models.json` and
 *     no live credentials ever enter fixtures, logs, or commits;
 *   - canonical projection — wall-clock/machine-specific fields are zeroed
 *     or dropped (timestamps, error stacks), JSON-carrying signatures are
 *     re-serialized with sorted keys, and the C++ comparator applies a float
 *     tolerance (see the README and `tests/support/PiEventSnapshot.hpp`).
 *
 * Usage (from anywhere):
 *   ../pi/node_modules/.bin/tsx fixtures/pi-coding-agent/capture/capture-gate-snapshots.mts
 * `PI_CHECKOUT` overrides the pi source checkout (default: sibling `../pi`);
 * `CCH_TEST_BINARY` overrides the C++ test binary (default:
 * `<repoRoot>/build/cpp_harness_tests`). The pi checkout MUST sit at the
 * frozen parity baseline commit and declare the pinned artifact version; the
 * script refuses to run otherwise.
 */

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Deterministic environment before any module that reads the home directory
// or terminal capabilities runs (same pins as the pi-ai/pi-tui sidecars).
process.env.HOME = "/home/tester";
process.env.USERPROFILE = "/home/tester";
delete process.env.TERM;
delete process.env.TERM_PROGRAM;
delete process.env.TERM_PROGRAM_VERSION;
delete process.env.KITTY_WINDOW_ID;
delete process.env.WEZTERM_PANE;
delete process.env.TMUX;

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const fixtureDir = path.resolve(scriptDir, "..");
const repoRoot = path.resolve(fixtureDir, "../..");
const piCheckout = process.env.PI_CHECKOUT ?? path.resolve(repoRoot, "../pi");
const FROZEN_COMMIT = "83114817c68f5413e4d7ba6d7003ddc511cd31d2";
const PINNED_PACKAGE = "@earendil-works/pi-coding-agent";
const PINNED_VERSION = "0.83.0";

// ── Frozen-checkout guard ─────────────────────────────────────────────────

const head = execFileSync("git", ["-C", piCheckout, "rev-parse", "HEAD"], {
	encoding: "utf8",
}).trim();
if (head !== FROZEN_COMMIT) {
	throw new Error(
		`pi checkout must be at the frozen baseline ${FROZEN_COMMIT}, found ${head}`,
	);
}

// The artifact pin is verified in the frozen checkout (ADR 0036, #420): the
// package declares the commit-correlated version at the frozen commit.
const codingAgentPackage = JSON.parse(
	readFileSync(
		path.join(piCheckout, "packages/coding-agent/package.json"),
		"utf8",
	),
) as { name: string; version: string };
if (
	codingAgentPackage.name !== PINNED_PACKAGE ||
	codingAgentPackage.version !== PINNED_VERSION
) {
	throw new Error(
		`frozen checkout must declare ${PINNED_PACKAGE}@${PINNED_VERSION}, ` +
			`found ${codingAgentPackage.name}@${codingAgentPackage.version}`,
	);
}

// ── Canonical projection (shared with the #421/#422 golden families) ───────

// Mirrors `fixtures/pi-ai/capture/capture-ts-events.mts` (R2 §7.8): the C++
// comparator (`tests/support/PiEventSnapshot.hpp`) applies the same
// projection on its side, so captures and comparisons stay byte-aligned.
//   - `timestamp` (messages and diagnostic entries) is wall-clock: zeroed.
//   - `diagnostics[].error.stack` is machine-specific: removed.
//   - Content-block parser scratch fields (`index`, `partialJson`,
//     `customInput`) live inside pi's mutated partial objects while streaming:
//     removed.
//   - `textSignature` / `thinkingSignature` strings that hold a JSON object
//     or array are re-serialized with recursively sorted keys (pi keeps
//     insertion order; the C++ surface serializes sorted maps).
//   - Numbers compare with a 1e-9 relative + 1e-12 absolute tolerance on the
//     C++ side; the snapshot stores the exact V8 values.

function canonicalStringify(value: unknown): string {
	if (Array.isArray(value)) {
		return `[${value.map((entry) => canonicalStringify(entry)).join(",")}]`;
	}
	if (value !== null && typeof value === "object") {
		const entries = Object.keys(value as Record<string, unknown>)
			.sort()
			.map(
				(key) =>
					`${JSON.stringify(key)}:${canonicalStringify(
						(value as Record<string, unknown>)[key],
					)}`,
			);
		return `{${entries.join(",")}}`;
	}
	return JSON.stringify(value) ?? "undefined";
}

/** Re-serializes signature strings that hold JSON with sorted keys. */
function canonicalSignature(signature: string): string {
	try {
		const parsed: unknown = JSON.parse(signature);
		if (parsed !== null && typeof parsed === "object") {
			return canonicalStringify(parsed);
		}
	} catch {
		// Not JSON: keep verbatim.
	}
	return signature;
}

const SCRATCH_KEYS = new Set(["index", "partialJson", "customInput"]);

/** Applies the canonical projection to one content block in place. */
export function normalizeContentBlock(block: Record<string, unknown>): void {
	for (const key of Object.keys(block)) {
		if (SCRATCH_KEYS.has(key)) {
			delete block[key];
		}
	}
	if (block.type === "text" && typeof block.textSignature === "string") {
		block.textSignature = canonicalSignature(block.textSignature);
	}
	if (block.type === "thinking" && typeof block.thinkingSignature === "string") {
		block.thinkingSignature = canonicalSignature(block.thinkingSignature);
	}
}

/** Applies the canonical projection to one message in place. */
export function normalizeMessage(message: Record<string, unknown>): void {
	message.timestamp = 0;
	if (Array.isArray(message.diagnostics)) {
		for (const diagnostic of message.diagnostics as Record<string, unknown>[]) {
			diagnostic.timestamp = 0;
			if (diagnostic.error) {
				delete (diagnostic.error as Record<string, unknown>).stack;
			}
		}
	}
	if (Array.isArray(message.content)) {
		for (const block of message.content as Record<string, unknown>[]) {
			normalizeContentBlock(block);
		}
	}
}

// ── Committed snapshots: interactive E2E goldens ───────────────────────────

// The committed CLI-level screen goldens (`e2e/boot.txt`, `e2e/turn.txt`) are
// generated by the C++ `InteractiveBootE2ETest` under `CCH_CAPTURE_GOLDENS=1`
// and byte-compared by the same test. The E2E workspace is the deterministic
// `cpp-harness-e2e-workspace` temp path (removed and recreated at boot), so
// the footer's pwd line stays byte-stable under the pinned environment.

const testBinary =
	process.env.CCH_TEST_BINARY ?? path.join(repoRoot, "build/cpp_harness_tests");
if (!existsSync(testBinary)) {
	throw new Error(
		`test binary not found at ${testBinary}; configure the build first ` +
			"(`cmake --preset vcpkg && cmake --build --preset vcpkg`) or set " +
			"CCH_TEST_BINARY",
	);
}

function runInteractiveE2e(capture: boolean): void {
	const env: Record<string, string> = {
		...process.env,
		HOME: "/home/tester",
		USERPROFILE: "/home/tester",
	};
	if (capture) env.CCH_CAPTURE_GOLDENS = "1";
	execFileSync(testBinary, ["[issue399]"], {
		stdio: "inherit",
		env,
		cwd: repoRoot,
	});
}

// Regenerate the goldens, then run the compare pass against the freshly
// written files: a nondeterministic capture fails the compare pass loudly.
runInteractiveE2e(true);
runInteractiveE2e(false);

// ── Committed snapshots: session- and value-suite goldens (#421) ────────────

// The session-family differential goldens (`fixtures/pi-coding-agent/sessions/`)
// are regenerated by `session-snapshots.mts`, which drives the frozen
// `packages/coding-agent` sources through the five scripted session scenarios
// (lifecycle, resume, compaction, model switching, session-family flows) at
// message/content-block level. It carries its own frozen-checkout guard, the
// resolution provisioning (workspace-package tsconfig paths + node_modules +
// generated model data), and a capture-then-byte-verify determinism pass. The
// C++ comparator is `tests/coding_agent/runtime/SessionSuiteGoldenTest.cpp`.
const sessionEnv: Record<string, string> = {
	...process.env,
	HOME: "/home/tester",
	USERPROFILE: "/home/tester",
	PI_CHECKOUT: piCheckout,
};
execFileSync(
	path.join(piCheckout, "node_modules/.bin/tsx"),
	[path.join(scriptDir, "session-snapshots.mts")],
	{
		stdio: "inherit",
		env: sessionEnv,
		cwd: repoRoot,
	},
);

console.log(
	"wrote fixtures/pi-coding-agent/e2e/boot.txt and fixtures/pi-coding-agent/e2e/turn.txt " +
		"(capture + byte-compare pass both green); " +
		"regenerated fixtures/pi-coding-agent/sessions/session-*.json (#421)",
);
