// Differential tests for the pi-tui completion gate (issue #386): byte-wise
// comparison of the C++ toolkit surfaces against the committed snapshots
// under `fixtures/pi-tui/` (input decode, keybinding table, terminal-image
// encoder, width/truncate/wrap/slice/strip utilities, fuzzy, and Markdown
// rendered output). The snapshots are generated by
// `fixtures/pi-tui/capture/capture-tui-snapshots.mts` from the frozen pi
// checkout at `83114817c68f5413e4d7ba6d7003ddc511cd31d2`; see
// `fixtures/pi-tui/README.md` for the capability-to-source checklist.
//
// The decode-at-edge rows pin the fork-A divergence: pi's raw-string
// `parseKey` identifiers are compared with the C++ typed decoder's
// `key_id()`/event types, the mode-dependent legacy re-readings are compared
// against the legacy column (the C++ decoder is single-table), and the
// recorded identifier divergences (uppercase letters, unshifted uppercase
// codepoints) are pinned to their C++ outcomes.

#include <cch/tui/Fuzzy.hpp>
#include <cch/tui/Keybindings.hpp>
#include <cch/tui/Markdown.hpp>
#include <cch/tui/TerminalImage.hpp>
#include <cch/tui/Utils.hpp>

#include "tui/InputDecoder.hpp"
#include "support/EnvVarGuard.hpp"
#include "support/ImageCapabilitiesGuard.hpp"
#include "tui/InteractionUtils.hpp"
#include "util/Json.hpp"

#include <catch2/catch_message.hpp>
#include <catch2/catch_test_macros.hpp>

#include <cstddef>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <memory>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

using namespace cch;

namespace {

[[nodiscard]] std::filesystem::path fixture_path(std::string_view name) {
    return std::filesystem::path{CCH_SOURCE_DIR} / "fixtures/pi-tui" / name;
}

[[nodiscard]] util::Expected<util::JsonValue> read_fixture(std::string_view name) {
    std::ifstream input{fixture_path(name), std::ios::binary};
    if (!input) {
        return std::unexpected(util::make_error(
            util::ErrorCode::Unknown,
            "Failed to open pi-tui fixture: " + fixture_path(name).string()));
    }
    const std::string json{
        std::istreambuf_iterator<char>{input},
        std::istreambuf_iterator<char>{}};
    return util::read_json(json);
}

[[nodiscard]] const util::JsonValue* field(
    const util::JsonValue::object_t& fields,
    std::string_view key) {
    const auto found = fields.find(std::string(key));
    return found == fields.end() ? nullptr : &found->second;
}

/// The decoded single event a full-buffer feed must produce for a key corpus
/// entry, projected exactly like the snapshot (`id` + `eventType`).
struct ExpectedKey {
    std::string id;
    std::string event_type;
};

[[nodiscard]] ExpectedKey expected_key(const util::JsonValue& entry) {
    const auto& expected = entry.get<util::JsonValue::object_t>().at("expected")
                               .get<util::JsonValue::object_t>();
    const auto& id = expected.at("id");
    return {
        .id = id.holds<std::string>() ? id.get_string() : std::string{},
        .event_type = expected.at("eventType").holds<std::string>()
            ? expected.at("eventType").get_string()
            : std::string{},
    };
}

[[nodiscard]] std::string event_type_name(tui::KeyEventType type) {
    switch (type) {
        case tui::KeyEventType::Press:
            return "press";
        case tui::KeyEventType::Repeat:
            return "repeat";
        case tui::KeyEventType::Release:
            return "release";
    }
    return {};
}

/// Feed `sequence` to a fresh decoder (with a trailing flush for lone ESC
/// prefixes that only resolve on flush, like pi's fragment timeout) and
/// return the single decoded key event, or `std::nullopt` when no key event
/// is produced.
[[nodiscard]] std::optional<tui::KeyEvent> decode_key(std::string_view sequence) {
    tui::detail::InputDecoder decoder;
    auto events = decoder.feed(sequence);
    const auto flushed = decoder.flush();
    events.insert(events.end(), flushed.begin(), flushed.end());
    if (events.size() != 1) return std::nullopt;
    const auto* key = std::get_if<tui::KeyEvent>(&events.front());
    return key == nullptr ? std::nullopt : std::optional<tui::KeyEvent>{*key};
}

} // namespace

TEST_CASE("input-decode corpus matches the frozen pi parseKey table", "[tui][differential][issue386]") {
    const auto fixture = read_fixture("input-decode.json");
    REQUIRE(fixture);
    const auto& root = fixture->get<util::JsonValue::object_t>();
    const auto& corpus = root.at("corpus").get<util::JsonValue::array_t>();
    REQUIRE_FALSE(corpus.empty());

    for (const auto& entry : corpus) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        const auto sequence = object.at("sequence").get_string();
        const auto expected = expected_key(entry);
        const auto context = std::string{"sequence "} + sequence;
        INFO(context);
        const auto key = decode_key(sequence);
        REQUIRE(key.has_value());
        CHECK(tui::key_id(*key) == expected.id);
        CHECK(event_type_name(key->type) == expected.event_type);
    }
}

TEST_CASE("mode-dependent legacy sequences decode to pi's legacy column", "[tui][differential][issue386]") {
    const auto fixture = read_fixture("input-decode.json");
    REQUIRE(fixture);
    const auto& root = fixture->get<util::JsonValue::object_t>();
    const auto& mode_dependent = root.at("modeDependent").get<util::JsonValue::array_t>();
    REQUIRE_FALSE(mode_dependent.empty());

    for (const auto& entry : mode_dependent) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        const auto sequence = object.at("sequence").get_string();
        const auto context = std::string{"sequence "} + sequence;
        INFO(context);
        const auto& legacy = object.at("legacy").get<util::JsonValue::object_t>();
        // The kitty column documents the mode-dependent re-reading; the C++
        // single-table decoder keeps the legacy reading (fixture README).
        REQUIRE(!legacy.at("id").get_string().empty());
        const auto key = decode_key(sequence);
        REQUIRE(key.has_value());
        CHECK(tui::key_id(*key) == legacy.at("id").get_string());
        CHECK(event_type_name(key->type) == legacy.at("eventType").get_string());
    }
}

TEST_CASE("recorded decode divergences pin the C++ outcomes", "[tui][differential][issue386]") {
    const auto fixture = read_fixture("input-decode.json");
    REQUIRE(fixture);
    const auto& root = fixture->get<util::JsonValue::object_t>();
    const auto& divergences = root.at("divergences").get<util::JsonValue::array_t>();
    REQUIRE_FALSE(divergences.empty());

    for (const auto& entry : divergences) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        const auto sequence = object.at("sequence").get_string();
        const auto& pi = object.at("pi").get<util::JsonValue::object_t>();
        const auto& pi_id_value = pi.at("id");
        const auto pi_id =
            pi_id_value.holds<std::string>() ? pi_id_value.get_string() : std::string{};
        const auto context = std::string{"sequence "} + sequence;
        INFO(context);
        const auto key = decode_key(sequence);
        REQUIRE(key.has_value());
        if (pi_id.size() == 1 && pi_id.front() >= 'A' && pi_id.front() <= 'Z') {
            // Uppercase letters: pi returns the raw text identifier ("A");
            // the C++ decoder canonicalizes to the shift+letter identifier
            // with the typed case preserved in inserted text
            // (detail::printable_text).
            const auto expected =
                std::string{"shift+"} + static_cast<char>(pi_id.front() - 'A' + 'a');
            CHECK(tui::key_id(*key) == expected);
            CHECK(key->shift);
            CHECK(tui::detail::printable_text(*key) == pi_id);
        } else {
            // Unshifted uppercase codepoints: pi rejects them (null); the
            // C++ decoder still decodes the uppercase character key. No
            // binding or printable path consumes these, so the divergence is
            // observable only at the decode layer itself.
            CHECK(!tui::key_id(*key).empty());
        }
    }
}

TEST_CASE("discarded control sequences produce no key events", "[tui][differential][issue386]") {
    const auto fixture = read_fixture("input-decode.json");
    REQUIRE(fixture);
    const auto& root = fixture->get<util::JsonValue::object_t>();
    const auto& discarded = root.at("discarded").get<util::JsonValue::array_t>();
    REQUIRE_FALSE(discarded.empty());

    for (const auto& entry : discarded) {
        const auto sequence = entry.get_string();
        INFO(std::string{"sequence "} + sequence);
        tui::detail::InputDecoder decoder;
        CHECK(decoder.feed(sequence).empty());
    }
}

TEST_CASE("bracketed-paste framing decodes to pi's paste framing", "[tui][differential][issue386]") {
    const auto fixture = read_fixture("input-decode.json");
    REQUIRE(fixture);
    const auto& root = fixture->get<util::JsonValue::object_t>();
    const auto& paste = root.at("paste").get<util::JsonValue::array_t>();
    REQUIRE_FALSE(paste.empty());

    for (const auto& entry : paste) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        const auto framed = object.at("framed").get_string();
        const auto content = object.at("content").get_string();
        const auto lines = static_cast<std::size_t>(object.at("lines").get_number());
        const auto context = std::string{"content "} + content;
        INFO(context);

        tui::detail::InputDecoder decoder;
        const auto events = decoder.feed(framed);
        REQUIRE(events.size() == 1);
        const auto* paste_event = std::get_if<tui::PasteEvent>(&events.front());
        REQUIRE(paste_event != nullptr);
        CHECK(paste_event->text == content);
        CHECK(paste_event->lines == lines);
        CHECK(paste_event->original_bytes == content.size());
        CHECK(!paste_event->truncated);
    }
}

TEST_CASE("chunk-split boundaries reassemble to the full-buffer decode", "[tui][differential][issue386]") {
    const auto fixture = read_fixture("input-decode.json");
    REQUIRE(fixture);
    const auto& root = fixture->get<util::JsonValue::object_t>();
    const auto& chunk_splits = root.at("chunkSplits").get<util::JsonValue::array_t>();
    REQUIRE_FALSE(chunk_splits.empty());

    for (const auto& entry : chunk_splits) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        const auto sequence = object.at("sequence").get_string();
        const auto chunk_size = static_cast<std::size_t>(object.at("chunkSize").get_number());
        const auto expected = expected_key(entry);
        const auto context = std::string{"sequence "} + sequence;
        INFO(context);

        tui::detail::InputDecoder decoder;
        std::vector<tui::InputEventVariant> events;
        for (std::size_t offset = 0; offset < sequence.size(); offset += chunk_size) {
            auto chunk_events = decoder.feed(sequence.substr(offset, chunk_size));
            events.insert(events.end(), chunk_events.begin(), chunk_events.end());
        }
        const auto flushed = decoder.flush();
        events.insert(events.end(), flushed.begin(), flushed.end());

        if (expected.id.empty()) {
            // The paste-framing chunk case: exactly one PasteEvent.
            REQUIRE(events.size() == 1);
            CHECK(std::get_if<tui::PasteEvent>(&events.front()) != nullptr);
            continue;
        }
        REQUIRE(events.size() == 1);
        const auto* key = std::get_if<tui::KeyEvent>(&events.front());
        REQUIRE(key != nullptr);
        CHECK(tui::key_id(*key) == expected.id);
        CHECK(event_type_name(key->type) == expected.event_type);
    }
}

TEST_CASE("assembled keybinding table matches pi's TUI_KEYBINDINGS", "[tui][differential][issue386]") {
    const auto fixture = read_fixture("keybindings.json");
    REQUIRE(fixture);
    const auto& entries = fixture->get<util::JsonValue::array_t>();

    const auto definitions = tui::builtin_tui_keybinding_definitions();
    REQUIRE(definitions.size() == 30);
    std::size_t assembled = 0;
    for (const auto& entry : entries) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        const auto id = object.at("id").get_string();
        INFO(id);
        if (tui::is_known_unassembled_tui_keybinding(id)) continue;
        ++assembled;

        auto definition = std::find_if(
            definitions.begin(),
            definitions.end(),
            [&](const auto& candidate) { return candidate.id == id; });
        REQUIRE(definition != definitions.end());
        CHECK(definition->description == object.at("description").get_string());

        const auto& keys = object.at("defaultKeys").get<util::JsonValue::array_t>();
        REQUIRE(definition->default_keys.size() == keys.size());
        for (std::size_t index = 0; index < keys.size(); ++index) {
            INFO(id + " key " + std::to_string(index));
            CHECK(
                definition->default_keys[index] == keys[index].get_string());
        }
    }
    CHECK(assembled == 30);
}

TEST_CASE("terminal-image encoder bytes match the frozen pi encoders", "[tui][differential][issue386]") {
    const auto fixture = read_fixture("image-encoder.json");
    REQUIRE(fixture);
    const auto& root = fixture->get<util::JsonValue::object_t>();

    const auto& kitty = root.at("kitty").get<util::JsonValue::array_t>();
    REQUIRE(kitty.size() == 2);
    for (const auto& entry : kitty) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        const auto base64 = object.at("base64").get_string();
        const auto output = object.at("output").get_string();
        const auto& options = object.at("options").get<util::JsonValue::object_t>();
        const auto columns = static_cast<std::size_t>(options.at("columns").get_number());
        const auto rows = static_cast<std::size_t>(options.at("rows").get_number());
        const auto image_id = static_cast<std::uint64_t>(options.at("imageId").get_number());
        const auto context = std::string{"kitty case "} + object.at("name").get_string();
        INFO(context);

        const auto encoded = tui::detail::encode_terminal_image(
            tui::InlineImageProtocol::Kitty,
            tui::TerminalImage{
                .encoded_data = base64,
                .mime_type = "image/png",
                .region = {.columns = columns, .rows = rows},
            },
            tui::TerminalImageHandle{.value = image_id});
        REQUIRE(encoded.has_value());
        CHECK(*encoded == output);
    }

    const auto& iterm2 = root.at("iterm2").get<util::JsonValue::array_t>();
    REQUIRE(iterm2.size() == 2);
    for (const auto& entry : iterm2) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        const auto base64 = object.at("base64").get_string();
        const auto output = object.at("output").get_string();
        const auto& options = object.at("options").get<util::JsonValue::object_t>();
        const auto columns = static_cast<std::size_t>(options.at("width").get_number());
        const auto rows = static_cast<std::size_t>(options.at("height").get_number());
        const auto* name = field(options, "name");
        const auto context = std::string{"iterm2 case "} + object.at("name").get_string();
        INFO(context);

        const auto encoded = tui::detail::encode_terminal_image(
            tui::InlineImageProtocol::ITerm2,
            tui::TerminalImage{
                .encoded_data = base64,
                .mime_type = "image/png",
                .filename = name == nullptr
                    ? std::optional<std::string_view>{}
                    : std::optional<std::string_view>{name->get_string()},
                .region = {.columns = columns, .rows = rows},
            },
            tui::TerminalImageHandle{.value = 1});
        REQUIRE(encoded.has_value());
        CHECK(*encoded == output);
    }

    const auto& hyperlinks = root.at("hyperlink").get<util::JsonValue::array_t>();
    for (const auto& entry : hyperlinks) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        CHECK(
            tui::hyperlink(object.at("text").get_string(), object.at("url").get_string()) ==
            object.at("output").get_string());
    }

    // Fallback text with a deterministic HOME and capability cache, exactly
    // as the capture script pinned them (the suite-wide Catch2 runner
    // isolation points HOME elsewhere).
    tests::EnvVarGuard home_guard{"HOME"};
    home_guard.set("/home/tester");
    const auto& fallback = root.at("fallback").get<util::JsonValue::array_t>();
    REQUIRE(fallback.size() == 4);
    for (const auto& entry : fallback) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        const auto hyperlinks_enabled = object.at("hyperlinks").get_boolean();
        const auto context = std::string{"fallback case "} + object.at("name").get_string();
        INFO(context);
        tests::ImageCapabilitiesGuard capabilities({
            .images = tui::InlineImageProtocol::Kitty,
            .hyperlinks = hyperlinks_enabled,
        });
        const auto* filename = field(object, "filename");
        const auto* dimensions = field(object, "dimensions");
        std::optional<tui::ImagePixelSize> size;
        if (dimensions != nullptr) {
            const auto& dims = dimensions->get<util::JsonValue::object_t>();
            size = tui::ImagePixelSize{
                .width = static_cast<std::size_t>(dims.at("widthPx").get_number()),
                .height = static_cast<std::size_t>(dims.at("heightPx").get_number()),
            };
        }
        const auto rendered = tui::image_fallback(
            "image/png",
            size,
            filename == nullptr
                ? std::optional<std::string_view>{}
                : std::optional<std::string_view>{filename->get_string()});
        CHECK(rendered == object.at("output").get_string());
    }
}

TEST_CASE("width truncate wrap slice strip match the frozen pi utils", "[tui][differential][issue386]") {
    const auto fixture = read_fixture("utils.json");
    REQUIRE(fixture);
    const auto& root = fixture->get<util::JsonValue::object_t>();

    const auto& visible = root.at("visibleWidth").get<util::JsonValue::array_t>();
    for (const auto& entry : visible) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        const auto context = std::string{"visibleWidth case "} + object.at("name").get_string();
        INFO(context);
        CHECK(
            tui::visible_width(object.at("input").get_string()) ==
                static_cast<std::size_t>(object.at("output").get_number()));
    }

    const auto& truncate = root.at("truncate").get<util::JsonValue::array_t>();
    for (const auto& entry : truncate) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        const auto context = std::string{"truncate case "} + object.at("name").get_string();
        INFO(context);
        const auto width = static_cast<std::size_t>(object.at("width").get_number());
        const auto ellipsis = object.at("ellipsis").get_string();
        const auto pad = object.at("pad").get_boolean();
        const auto output = tui::truncate_text(object.at("input").get_string(), width, ellipsis, pad);
        REQUIRE(output.has_value());
        CHECK(*output == object.at("output").get_string());
    }

    const auto& wrap = root.at("wrap").get<util::JsonValue::array_t>();
    for (const auto& entry : wrap) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        const auto context = std::string{"wrap case "} + object.at("name").get_string();
        INFO(context);
        const auto output = tui::wrap_text(
            object.at("input").get_string(),
            static_cast<std::size_t>(object.at("width").get_number()));
        REQUIRE(output.has_value());
        const auto& expected = object.at("output").get<util::JsonValue::array_t>();
        REQUIRE(output->size() == expected.size());
        for (std::size_t index = 0; index < expected.size(); ++index) {
            CHECK((*output)[index] == expected[index].get_string());
        }
    }

    const auto& slice = root.at("slice").get<util::JsonValue::array_t>();
    for (const auto& entry : slice) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        const auto context = std::string{"slice case "} + object.at("name").get_string();
        INFO(context);
        const auto output = tui::slice_by_column(
            object.at("input").get_string(),
            static_cast<std::size_t>(object.at("start").get_number()),
            static_cast<std::size_t>(object.at("length").get_number()),
            object.at("strict").get_boolean());
        REQUIRE(output.has_value());
        CHECK(*output == object.at("output").get_string());
    }

    const auto& strip = root.at("strip").get<util::JsonValue::array_t>();
    for (const auto& entry : strip) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        const auto context = std::string{"strip case "} + object.at("name").get_string();
        INFO(context);
        CHECK(
            tui::strip_terminal_sequences(object.at("input").get_string()) ==
                object.at("output").get_string());
    }
}

TEST_CASE("fuzzy match and filter match the frozen pi fuzzy outputs", "[tui][differential][issue386]") {
    const auto fixture = read_fixture("fuzzy.json");
    REQUIRE(fixture);
    const auto& root = fixture->get<util::JsonValue::object_t>();

    const auto& match = root.at("match").get<util::JsonValue::array_t>();
    for (const auto& entry : match) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        const auto context = std::string{"query "} + object.at("query").get_string() +
            " in " + object.at("text").get_string();
        INFO(context);
        const auto& expected = object.at("output").get<util::JsonValue::object_t>();
        const auto result =
            tui::fuzzy_match(object.at("query").get_string(), object.at("text").get_string());
        CHECK(result.matches == expected.at("matches").get_boolean());
        CHECK(result.score == expected.at("score").get_number());
    }

    const auto& filter = root.at("filter").get<util::JsonValue::array_t>();
    for (const auto& entry : filter) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        const auto context = std::string{"fuzzy filter "} + object.at("name").get_string();
        INFO(context);
        const auto& items = object.at("items").get<util::JsonValue::array_t>();
        std::vector<std::string> items_vector;
        for (const auto& item : items) items_vector.push_back(item.get_string());
        const auto query = object.at("query").get_string();
        const auto ranked = tui::fuzzy_filter(items_vector, query, [](const std::string& item) {
            return item;
        });
        const auto& expected = object.at("output").get<util::JsonValue::array_t>();
        REQUIRE(ranked.size() == expected.size());
        for (std::size_t index = 0; index < expected.size(); ++index) {
            CHECK(ranked[index] == expected[index].get_string());
        }
    }
}

TEST_CASE("markdown rendered output matches the frozen pi component", "[tui][differential][issue386]") {
    const auto fixture = read_fixture("markdown.json");
    REQUIRE(fixture);
    const auto& root = fixture->get<util::JsonValue::object_t>();

    // Rebuild the recorded deterministic theme as hooks. pi composes
    // `theme.link(theme.underline(...))` for link text; the C++ `link_text`
    // role receives the plain label, so the composition moves into the hook.
    const auto& styles = root.at("styles").get<util::JsonValue::object_t>();
    const auto wrap_style = [&](std::string_view name) {
        const auto& style = styles.at(std::string(name)).get<util::JsonValue::object_t>();
        const auto prefix = style.at("prefix").get_string();
        const auto suffix = style.at("suffix").get_string();
        return [prefix, suffix](std::string text) { return prefix + text + suffix; };
    };
    tui::MarkdownStyleConfig style;
    style.heading = wrap_style("heading");
    style.emphasis = wrap_style("italic");
    style.strong = wrap_style("bold");
    style.strikethrough = wrap_style("strikethrough");
    style.inline_code = wrap_style("code");
    style.code_block = wrap_style("codeBlock");
    style.code_block_border = wrap_style("codeBlockBorder");
    style.list_marker = wrap_style("listBullet");
    // pi's blockquote rendering applies the quote style twice (the quote
    // block's style context wraps the paragraph's own); the C++ renderer
    // applies the role once, so the composition moves into the hook.
    const auto italic = wrap_style("italic");
    style.quote = [italic](std::string text) {
        return italic(italic(std::move(text)));
    };
    style.quote_border = wrap_style("quoteBorder");
    style.horizontal_rule = wrap_style("hr");
    const auto underline = wrap_style("underline");
    const auto link_text = wrap_style("link");
    style.link_text = [underline, link_text](std::string text) {
        return link_text(underline(std::move(text)));
    };
    style.link_url = wrap_style("linkUrl");
    style.link = [](std::string text, std::string_view destination) {
        return tui::hyperlink(std::move(text), destination);
    };
    style.code_block_indent = "  ";

    // The capture pinned hyperlinks=true for the link rendering.
    tests::ImageCapabilitiesGuard capabilities({
        .images = tui::InlineImageProtocol::Kitty,
        .hyperlinks = true,
    });

    const auto& cases = root.at("cases").get<util::JsonValue::array_t>();
    tui::Markdown markdown({}, 0, 0, std::move(style));
    for (const auto& entry : cases) {
        const auto& object = entry.get<util::JsonValue::object_t>();
        const auto width = static_cast<std::size_t>(object.at("width").get_number());
        const auto context = std::string{"markdown case "} + object.at("name").get_string();
        INFO(context);

        markdown.set_text(object.at("markdown").get_string());
        const auto rendered = markdown.render(width);
        REQUIRE(rendered.has_value());
        const auto& expected = object.at("lines").get<util::JsonValue::array_t>();
        REQUIRE(rendered->lines.size() == expected.size());
        for (std::size_t index = 0; index < expected.size(); ++index) {
            CHECK(rendered->lines[index] == expected[index].get_string());
        }
    }
}
