if(NOT DEFINED CCH_SOURCE_DIR)
    message(FATAL_ERROR "CCH_SOURCE_DIR is required")
endif()
if(NOT DEFINED CCH_TEST_CASE)
    message(FATAL_ERROR "CCH_TEST_CASE is required")
endif()

include("${CCH_SOURCE_DIR}/cmake/SupportedBuild.cmake")

if(CCH_TEST_CASE STREQUAL "accept-gcc")
    cch_validate_compiler_role("build" "GNU" "16.0.1")
    cch_validate_configuration_role("build" "Release")
elseif(CCH_TEST_CASE STREQUAL "accept-clang")
    cch_validate_compiler_role("conformance" "Clang" "22.1.8")
    cch_validate_configuration_role("conformance" "Debug")
elseif(CCH_TEST_CASE STREQUAL "reject-cross-build")
    cch_validate_platform("Linux" "x86_64" TRUE "" "" TRUE)
elseif(CCH_TEST_CASE STREQUAL "reject-operating-system")
    cch_validate_platform("Darwin" "x86_64" FALSE "" "" TRUE)
elseif(CCH_TEST_CASE STREQUAL "reject-architecture")
    cch_validate_platform("Linux" "aarch64" FALSE "" "" TRUE)
elseif(CCH_TEST_CASE STREQUAL "reject-libc")
    cch_validate_platform("Linux" "x86_64" FALSE "" "" FALSE)
elseif(CCH_TEST_CASE STREQUAL "reject-generator")
    cch_validate_generator("Unix Makefiles" "4.4" FALSE)
elseif(CCH_TEST_CASE STREQUAL "reject-ninja-version")
    cch_validate_generator("Ninja" "1.10.2" FALSE)
elseif(CCH_TEST_CASE STREQUAL "reject-unity")
    cch_validate_generator("Ninja" "1.13.2" TRUE)
elseif(CCH_TEST_CASE STREQUAL "reject-gcc-version")
    cch_validate_compiler_role("build" "GNU" "15.2.0")
elseif(CCH_TEST_CASE STREQUAL "reject-clang-version")
    cch_validate_compiler_role("conformance" "Clang" "21.1.0")
elseif(CCH_TEST_CASE STREQUAL "reject-clang-build-role")
    cch_validate_compiler_role("build" "Clang" "22.1.8")
elseif(CCH_TEST_CASE STREQUAL "reject-clang-release")
    cch_validate_configuration_role("conformance" "Release")
elseif(CCH_TEST_CASE STREQUAL "reject-dependency-fallback")
    cch_validate_vcpkg_dependency_path(
        "OpenSSL"
        "/tmp/vcpkg-installed/x64-linux"
        "/usr/lib/x86_64-linux-gnu")
elseif(CCH_TEST_CASE STREQUAL "reject-missing-vcpkg-toolchain")
    cch_validate_vcpkg_shape("" TRUE TRUE "x64-linux")
elseif(CCH_TEST_CASE STREQUAL "reject-vcpkg-manifest-install")
    cch_validate_vcpkg_shape("/tmp/vcpkg/scripts/buildsystems/vcpkg.cmake" TRUE FALSE "x64-linux")
elseif(CCH_TEST_CASE STREQUAL "reject-vcpkg-host-triplet")
    cch_validate_vcpkg_options("arm64-linux" "" "" "")
elseif(CCH_TEST_CASE STREQUAL "reject-vcpkg-overlays")
    cch_validate_vcpkg_options("x64-linux" "/tmp/ports" "" "")
else()
    message(FATAL_ERROR "Unknown CCH_TEST_CASE: ${CCH_TEST_CASE}")
endif()
