#!/usr/bin/env tsx
/**
 * Generates `src/tui/CjkBreakRanges.inc`, the code-point range table of pi's
 * CJK line-break set (issue #705).
 *
 * pi makes a grapheme its own wrap token when it matches `cjkBreakRegex`
 * (`packages/tui/src/utils.ts:54` at the frozen baseline): the
 * `Script_Extensions` sets of Han, Hiragana, Katakana, Hangul, and Bopomofo.
 * `utf8proc` exposes no `Script_Extensions` data, so the set is carried as
 * generated range data instead of being re-derived in C++.
 *
 * Usage (from the repository root):
 *   PI_CHECKOUT=/path/to/frozen/pi \
 *     /path/to/frozen/pi/node_modules/.bin/tsx \
 *     fixtures/pi-tui/capture/generate-cjk-break-ranges.mts
 *
 * `PI_CHECKOUT` defaults to the sibling `../pi`. The checkout MUST sit at the
 * frozen parity baseline commit; the script refuses to run otherwise, and it
 * refuses to emit when the frozen regex source is not the text the provenance
 * header records.
 */

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const fixtureDir = path.resolve(scriptDir, "..");
const repoRoot = path.resolve(fixtureDir, "../..");
const piCheckout = process.env.PI_CHECKOUT ?? path.resolve(repoRoot, "../pi");
const FROZEN_COMMIT = "83114817c68f5413e4d7ba6d7003ddc511cd31d2";
const REGEX_SOURCE =
	"[\\p{Script_Extensions=Han}\\p{Script_Extensions=Hiragana}\\p{Script_Extensions=Katakana}\\p{Script_Extensions=Hangul}\\p{Script_Extensions=Bopomofo}]";
const OUTPUT = path.resolve(repoRoot, "src/tui/CjkBreakRanges.inc");

const head = execFileSync("git", ["-C", piCheckout, "rev-parse", "HEAD"], {
	encoding: "utf8",
}).trim();
if (head !== FROZEN_COMMIT) {
	throw new Error(
		`pi checkout must be at the frozen baseline ${FROZEN_COMMIT}, found ${head}`,
	);
}

const utilsPath = pathToFileURL(
	path.join(piCheckout, "packages/tui/src/utils.ts"),
).href;
const { cjkBreakRegex } = (await import(utilsPath)) as {
	cjkBreakRegex: RegExp;
};

if (cjkBreakRegex.source !== REGEX_SOURCE || !cjkBreakRegex.flags.includes("u")) {
	throw new Error(
		`frozen cjkBreakRegex source is ${cjkBreakRegex.source} (flags ${cjkBreakRegex.flags}); ` +
			`the provenance header records ${REGEX_SOURCE}`,
	);
}

interface CodepointRange {
	first: number;
	last: number;
}

const ranges: CodepointRange[] = [];
for (let codepoint = 0; codepoint <= 0x10ffff; codepoint++) {
	if (!cjkBreakRegex.test(String.fromCodePoint(codepoint))) {
		continue;
	}
	const previous = ranges[ranges.length - 1];
	if (previous && previous.last + 1 === codepoint) {
		previous.last = codepoint;
	} else {
		ranges.push({ first: codepoint, last: codepoint });
	}
}

if (ranges.length === 0) {
	throw new Error("frozen cjkBreakRegex matched no code point");
}

const hex = (codepoint: number): string =>
	`0x${codepoint.toString(16).toUpperCase()}`;

const header = `// Generated by fixtures/pi-tui/capture/generate-cjk-break-ranges.mts — do not edit.
//
// The code-point ranges pi's CJK line-break set matches, taken from
// \`cjkBreakRegex\` in packages/tui/src/utils.ts:54 at the frozen parity
// baseline ${FROZEN_COMMIT}:
//
//   /${REGEX_SOURCE}/u
//
// i.e. the Script_Extensions sets of Han, Hiragana, Katakana, Hangul, and
// Bopomofo. utf8proc exposes no Script_Extensions data, so the set is carried
// here as generated ranges rather than re-derived.
//
// Regenerate with (PI_CHECKOUT names the frozen pi checkout, and the
// generator runs under that checkout's node_modules/.bin/tsx):
//
//   PI_CHECKOUT=/path/to/frozen/pi tsx fixtures/pi-tui/capture/generate-cjk-break-ranges.mts
//
// Each entry is a closed code-point range, in ascending order and
// non-overlapping; CCH_CJK_BREAK_RANGE is defined at the include site.

`;

const body = ranges
	.map(({ first, last }) => `CCH_CJK_BREAK_RANGE(${hex(first)}, ${hex(last)})\n`)
	.join("");

writeFileSync(OUTPUT, `${header}${body}`);
console.log(
	`wrote src/tui/CjkBreakRanges.inc: ${ranges.length} ranges, ${ranges.reduce(
		(count, { first, last }) => count + (last - first + 1),
		0,
	)} code points`,
);
